name: fused-effects-async
version: 0.1.0.0
github: "poscat0x04/fused-effects-async"
license: BSD3
author: "Poscat"
maintainer: "poscat@mail.poscat.moe"
copyright: "2020 Poscat"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/poscat0x04/fused-effects-async#readme>

dependencies:
  - base >= 4.7 && < 5
  - async
  - fused-effects

library:
  source-dirs: src

tests:
  fused-effects-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fused-effects-async
